### ISSUE TITLE
Feature request: Additional notification info

### ISSUE THREAD

**Issue by Lanzones** [owntracks/ios#594]
Hi,

I was able to get my lora devices trigger an own track notification whenever it enters or leave a waypoint using the type:transition. 
Just wondering if their is a special type for additional information that I can use to push notification to alert user for critical battery levels and some other stuff.. at the moment I am concatenating the battery level and TID whenever the devices are transitioning in/out the waypoints to alert me the levels of the battery. Not a good way of doing it but it is acceptable at this stage.

Also, I just notice that the notification doesnt get stored at the notification centre even if I enabled it at the notification settings. Is this expected?

Jose

**Comment by jpmens** [comment]
What you might want to look at on our iOS app is the [featured](https://owntracks.org/booklet/features/featured/) feature which would allow you to notify your iOS device specifically. At the bottom of that page is a link to a more explicit example.

**Comment by ckrey** [comment]
Regarding "notification doesn't get stored": There was a reason not to store notifications when we implemented it years ago. Will review this and come back to you

**Comment by Lanzones** [comment]
Thanks will try your suggestions.. 
regarding stored notification, it will be relevant for devices that check in once or couple of times a day. Maybe these devices we dont care and monitor much until it moves or something get critical in the operation/location. Notification of these kind should be stored i reckon.

If we can have limit of say 5 recent notification stored fifoed in the notification centre that would be good..

Lanz

**Comment by Lanzones** [comment]
Hi,
Just quickly publish to my mqtt with topic owntracks/test2/lew-is/cmd and payload {"action": "action", "content": "hello there!", "_type": "cmd"}. I couldn't get the featured tab working on my ios app.. it doesnt seem to appear. I have tried a type transition and it did show me the notification. I have tried the cmd type again and it still doesnt work.. Could you help please.

Lanz

**Comment by jpmens** [comment]
I haven’t checked payload but make sure you publish with QoS>0

**Comment by Lanzones** [comment]
It was the topic.. it just should have been “owntracks/test2/“. 

Btw, do you have reference for formatting of the content similar to the example shown under that featured tab  writtin by chris? It looks what i wanted to do..

**Comment by jpmens** [comment]
Not sure I understand your question ... the content is HTML-formatted so you ought to be able to use any pertaining documentation; we don't specifically document it.

**Comment by Lanzones** [comment]
Hi 

Thanks. 

Everything is working as expected on the feature2 except i dont know how to get rid of that margin on the right and bottom.. the photos below is when i pinched screen to show that there is some sort of margin within the app.. i would like to display it to the centre and use the whole canvas as much as possible..

**Comment by jpmens** [comment]
Photos attached to email responses to github aren't added to an issue. :) But be aware, I'm not an HTML/CSS stylist so will likely not be able to help.

**Comment by Lanzones** [comment]
Hi, 
thanks didnt know that.. I am attaching to this response instead.. Maybe Chris would know how to adjust this feature page?
![IMG_E9307](https://user-images.githubusercontent.com/43723964/64106366-621a9b00-cdbb-11e9-85d5-8f386ab498bf.JPG)

**Comment by ckrey** [comment]
@Lanzones your last remark is a bug for all devices larger than an iPhoneSE. I opened up a separate issue for that
